#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# **************************************************************************** #
# This file is part of the pdpy project
# Copyright (C) 2021 Fede Camara Halac
# **************************************************************************** #
""" Mostly string parsing utilities """
# automatically generated by make_imports.sh
# on Wed Dec 22 20:51:48 -03 2021
from .utils import *
from .regex import *
from .arrange1b import *
