#!/bin/bash
# **************************************************************************** #
# This file is part of the pdpy project
# Copyright (C) 2021 Fede Camara Halac
# **************************************************************************** #
if [ ! $1 ]; then
    echo "Usage: ./make_imports.sh <path_to_pdpy_repo>"
    exit 1
fi
for i in . classes parse util; do
  echo >> "$1/$i/__init__.py"
  echo "# automatically generated by make_imports.sh" >> "$1/$i/__init__.py"
  echo "# on" $(date) >> "$1/$i/__init__.py"
  ./imports.sh "$1/$i" >> "$1/$i/__init__.py"
  echo >> "$1/$i/__init__.py"
done