#!/bin/bash

version=$(python -c "from scripts.version import get_version;print('.'.join(map(lambda x:str(x), get_version()[0])))")

printf "# Automatically generated by make_setup.sh
from distutils.core import setup
setup(name=\'pdpy-lib\',version=\'%s\')
" ${version}
