#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# **************************************************************************** #
# This file is part of the pdpy project
# Copyright (C) 2021 Fede Camara Halac
# **************************************************************************** #
""" Mostly transcoding stuff """
# automatically generated by make_imports.sh
# on Wed Dec 22 20:51:48 -03 2021
from .pdpy2json import *

